# Generated by Django 4.2.8 on 2024-06-20 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название записи')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Полный текст записи')),
                ('thumbnail', models.ImageField(blank=True, default='default.jpg', upload_to='images/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение записи')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус записи')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Прикреплено')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_post', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_post', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'СтатьяБлог',
                'verbose_name_plural': 'СтатьиБлога',
                'db_table': 'posts_blog',
                'ordering': ['-fixed', '-create'],
                'indexes': [models.Index(fields=['-fixed', '-create', 'status'], name='posts_blog_fixed_19b574_idx')],
            },
        ),
    ]
