# Generated by Django 4.2.8 on 2024-06-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
