# Generated by Django 4.2.8 on 2024-06-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bannerindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerindex',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
