# Generated by Django 4.2.8 on 2024-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_category_options_category_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerindex',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
